apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

# Container Runtime
containerRuntimeEndpoint: unix:///var/run/cri-dockerd.sock

# Static Pods:
staticPodPath: /etc/kubernetes/manifests

# Authentication & Authorization (permissive for standalone mode)
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow

# Resource Management (disabled - no systemd)
cgroupsPerQOS: false
cgroupDriver: cgroupfs
enforceNodeAllocatable: []

# Eviction (disabled - containerized environment)
evictionHard: {}

# Image Management (disabled GC)
imageGCHighThresholdPercent: 100

# Storage
failSwapOn: false
localStorageCapacityIsolation: false

# TLS
rotateCertificates: false
serverTLSBootstrap: false

# Node Registration
registerNode: true

# Networking (explicit defaults for CNI compatibility)
hairpinMode: hairpin-veth # Must match cri-dockerd --hairpin-mode
makeIPTablesUtilChains: true

# Pod Limits
maxPods: 110

# CPU Management
cpuCFSQuota: true

# Kernel Settings (cannot modify in container)
protectKernelDefaults: false

# Shutdown (no graceful shutdown without systemd)
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s

# 5 Minute Heartbeats (all sync/status intervals aligned)
# Reduces API traffic - pods/nodes reconciled via syncFrequency instead of watches
syncFrequency: 5m
nodeStatusUpdateFrequency: 5m
nodeStatusReportFrequency: 5m
nodeLeaseDurationSeconds: 300

# ConfigMap/Secret Detection (direct API calls instead of per-object watches)
configMapAndSecretChangeDetectionStrategy: Get
